### ISSUE TITLE
Enemylist seems inflated

### ISSUE THREAD

**Issue by ArchfiendNZ** [tirem/ConsolidatedUI#3]
I may just not understand how this works, but I just started leveling a new job and it seems to register every monster in the area instead of those I am engaged with, screenshot attached.
![enemylist](https://user-images.githubusercontent.com/93624292/211002174-93bedc17-f311-4508-b9a6-9b43120ce935.jpg)

**Comment by ArchfiendNZ** [comment]
Using the latest zip
Which config do you want? Script: default.txt?

**Comment by tirem** [comment]
game/config/addons/consolidatedui/[yourcharactersnane_####}.ini

**Comment by ArchfiendNZ** [comment]
Fixed in latest release
