### ISSUE TITLE
Debuffs not falling off 

### ISSUE THREAD

**Issue by CroftBond** [tirem/ConsolidatedUI#7]
![image](https://user-images.githubusercontent.com/122686154/212479850-e90aef82-ef5c-44e1-a4f4-ffabd2255bf2.png)

**Comment by CroftBond** [comment]
Note paralysis fell off enemy, but icon remained on mob (on both enemy list and target, forgot to select in picture)

**Comment by tirem** [comment]
This is the right place :)
So debuffs are tracked using packets so it's not going to be 100% accurate but if you notice something consistent that's something that can probably be fixed / improved.
Do you notice this everytime with paralysis or a specific enemy?

**Comment by CroftBond** [comment]
So more info. I was trying to recreate, and it seems that Paralysis (so far) has been the one that hasn't falled off, however it DOES eventually fall off. So the timer of the effect must be off. Slow, and Dia icons fall off at the right time. When I can sub /blm I'll test more debuffs.

**Comment by tirem** [comment]
Should be fixed in the most recent version :) ty for the report
